#17178 - browser update - sep2018
regru/browser-update-cleaned-up pull request #1
Opened 2018-09-18 17:38 UTC by AnDeVerin

@podkot @shifteee

2018-09-18 20:09 UTC, shifteee requested changes
You lose some improvements from prev version

2018-09-19 10:28 UTC, podkot commented
which improvements have been lost? lgtm at the moment

2018-09-19 14:24 UTC, AnDeVerin commented
@shifteee 
Commented test call in `update.npm.full.js`

2018-09-19 14:34 UTC, shifteee approved these changes

2018-09-19 14:34 UTC, shifteee commented on update.npm.full.js
> -};/*
this branch of code should be remover or commented

2018-09-19 14:39 UTC, merged